spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/management
    username: management
    password: management
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8086
